package dtos;

import com.emu.rule_engine_ms.service.dto.Member;
import com.emu.rule_engine_ms.service.dto.StpMessageDTO;
import com.emu.rule_engine_ms.service.utils.RuleUtils;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
global com.emu.rule_engine_ms.service.utils.RuleUtils ruleUtils;

	rule "Member_email_validation"
     when 
         mem: Member( email not matches "^(.+)@(.+)$" ) 
     then 
			 StpMessageDTO res = ruleUtils.getStpMessage("Member_email_validation");
			 insert(res);
    end  


	rule "Member_phone_validation"
		 when 
			mem: Member( phone not matches "(01)[0-9]{9}" )
		 then 
			StpMessageDTO res = ruleUtils.getStpMessage("Member_phone_validation"); 
			insert(res);
		 end
		 
	rule "Member_calcus"
		 when 
			mem: Member (id !=0)
		 then 
			//StpMessageDTO res = ruleUtils.getStpMessage("Member_email_validation");
			a(mem);
			ruleUtils.printHelloWorld(mem.getFirstName());
			ruleUtils.printHelloWorld(mem.getLastName());
			insert(res);
         end  
		 
	function void a(Member mem){
	            Instant instant=Instant.now();
                LocalDateTime ldt1 = LocalDateTime.ofInstant(instant, ZoneId.systemDefault());
                LocalDateTime ldt2 = LocalDateTime.ofInstant(mem.getBirthDate(), ZoneId.systemDefault());
				int years=(ldt1.getYear()-ldt2.getYear());
				double sal=years*5;
				mem.setFirstName("this is first name: "+sal);
				mem.setLastName("this is last name");
			}